### ISSUE TITLE
Create TrueCopy pair with provisioned_secondary_volume_id seems broken in 4.6.1

### ISSUE THREAD

**Issue by Darren-Chambers** [hitachi-vantara/vspone-block-ansible#187]
Hi,

After updating to 4.6.1 from 4.6.0 I am experiencing issues with hv_truecopy module.

Condition:
'Create TrueCopy pair with provisioned_secondary_volume_id'

"/tmp/ansible_hitachivantara.vspone_block.vsp.hv_truecopy_payload_bk1qx5qe/ansible_hitachivantara.vspone_block.vsp.hv_truecopy_payload.zip/ansible_collections/hitachivantara/vspone_block/plugins/module_utils/provisioner/vsp_true_copy_provisioner.py", line 754, in create_true_copy
    raise ValueError(err_msg)

"msg": "Failed to create the TrueCopy pair.'NoneType' object has no attribute 'hostGroupName'",

**Comment by Darren-Chambers** [comment]
I located the problem: models/vsp_host_group_models.py
Line 246:
self.portId = kwargs.get("port")
Update to:
self.portId = kwargs.get("portId")

**Comment by rsahuHitachi** [comment]
Hi @Darren-Chambers, This issue has been fixed on 4.7.0 version. Please verify and let us know.

**Comment by halbaHV** [comment]
This is working in latest 4.8.x.
